FROM 192.168.24.1:8787/rhosp12/openstack-mariadb-docker:{{ puddle.stdout }}

USER root
RUN curl -O http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm && rpm -ivh rhos-release-latest.noarch.rpm && rhos-release 12-director -d
RUN yum -y remove mariadb-server && yum -y install mariadb-galera-server
RUN rm /etc/my.cnf.d/server.cnf
USER mysql
